### ISSUE TITLE
write_int should take arbitrarily sized rust ints or some bignum

### ISSUE THREAD

**Issue by alex** [alex/rust-asn1#3]
Plan: new Integer interface here that we implement serialization code for.

**Comment by frewsxcv** [comment]
I thought I would have enough time to look into this today, but I didn't get around to it. Might as well mention though that there is a Rust library offering bignum support:

* https://doc.rust-lang.org/num/num/bigint/struct.BigInt.html
* https://doc.rust-lang.org/num/num/bigint/struct.BigUint.html
* https://github.com/rust-lang-deprecated/num ([more info here about 'deprecated'](https://internals.rust-lang.org/t/psa-movement-of-rust-lang-crates/2671))
