### ISSUE TITLE
Parsing DEFINED BY structure

### ISSUE THREAD

**Issue by mtodescato** [alex/rust-asn1#326]
I'am not finding any example on how to parse a sequnce like the following:
```rust
QCStatement::= SEQUENCE {
    statementId OBJECT IDENTIFIER,
    statementInfo ANY DEFINED BY statementId OPTIONAL
}
``` 

I built a the structs like this:
```rust
#[derive(Debug, asn1::Asn1Read, asn1::Asn1Write)]
pub struct QCStatement<'a> {
    statement_id: asn1::ObjectIdentifier,
    statement_info: Option<StatementInfo<'a>>,
}

#[derive(Debug, asn1::Asn1Read, asn1::Asn1Write)]
pub enum StatementInfo<'a> {
    QcEuRetentionPeriod(u32),
    MonetaryValue(MonetaryValue<'a>),
    QcType(QcType),
    PSD2QcType(PSD2QcType<'a>),
    QcEuPDS(PdsLocations<'a>),
}
``` 
The parser seems able to choose between the u32 and the MonetaryValue, but it's not able to choose between the complex types.
As i get this error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: UnexpectedTag { actual: Tag { value: 6, constructed: false, class: Universal } }, location: [4, "QCStatement::statement_info", "StatementInfo::MonetaryValue", "MonetaryValue::currency"] }'`

At this point I am trying to manually implement the parsing for the QCStatement<'a> as follows:
```rust
impl<'a> SimpleAsn1Readable<'a> for QCStatement<'a> {
    const TAG: asn1::Tag = asn1::Tag::primitive(0x20);
    #[inline]
    fn parse_data(data: &'a [u8]) -> asn1::ParseResult<QCStatement<'a>> {
        asn1::parse_single::<QCStatement<'a>>(data)
        asn1::parse(data, |d| {
            let statement_id = d.read_element::<asn1::ObjectIdentifier>()?;
            let statement_info = match statement_id.to_string().as_str() {
                "0.4.0.1862.1.2" => Option::Some(StatementInfo::MonetaryValue(
                    d.read_element::<MonetaryValue>()?,
                )),
                "0.4.0.1862.1.5" => {
                    Option::Some(StatementInfo::QcEuPDS(d.read_element::<PdsLocations>()?))
                }
                "0.4.0.1862.1.6" => {
                    Option::Some(StatementInfo::QcType(d.read_element::<QcType>()?))
                }
                "0.4.0.1862.1.3" => {
                    Option::Some(StatementInfo::QcEuRetentionPeriod(d.read_element::<u32>()?))
                }
                &_ => None,
            };
            return Ok(QCStatement::new(statement_id, statement_info));
        })
    }
}
``` 
But I'm not sure it's the intended way as it seems that even thought the struct are correct I constantly get unexpected tag.

**Comment by alex** [comment]
Ooops, I somehow lost track of this thread. Sorry for the slow response. Can you provide a full working example with input data?

The error you're seeing there is telling you that something had an OBJECT IDENTIFIER tag, when you were expecting something else, so it's hard to say where exactly the problem is without more context.

**Comment by mtodescato** [comment]
I should be able to create a minimal example. But really my point is since in asn1 is not an uncommon pattern to use the DEFINED BY as i QCStatements
```
QCStatement::= SEQUENCE {
    statementId OBJECT IDENTIFIER,
    statementInfo ANY DEFINED BY statementId OPTIONAL
}
```
What is your intended way to parse a file containing this kind of structures. Right now I'm parsing everything as sequenceOf<Sequence> so i can parse one by one checking the oid before, is it the only way?

**Comment by mtodescato** [comment]
I would be useful to have a declarative way of doing this. But for now basically i have tried both you solutions in a little different way :

- I parsed the valued as `SequenceOF<Sequence>` it seems to work for now, do you have an example using `asn1::Tlv`?
- I tried implementing  `SimpleAsn1Readable` but for some reason it was never called.

For the implementation of the declarative way I think that the most natural way of doing this is to declare an enum with the possible types. It is not so obvious how to choose between the enum elements as I can't see an easy way to declare inside the enum the data to make an efficient choice, otherwise you will need to parse with trial and error with would not be efficient. 
We could try to design something if you think we could add an API for this since to me it seems something used often.

**Comment by alex** [comment]
https://github.com/pyca/cryptography/blob/main/src/rust/src/x509/csr.rs#L32-L40 is an example of parsing things as `Tlv`.

**Comment by alex** [comment]
Can you provide a complete example and data to test with?

The pattern you have there is roughly correct, though you probably want to
match on Oid constants instead of strings.

The Unexpected Tag is telling you you got a tag of 6 (object identifier)
where something else was expected.

בתאריך יום ד׳, 7 בספט׳ 2022, 5:54, מאת matteotodescato ‏<
***@***.***>:

**Comment by mtodescato** [comment]
Unfortunately I think i can't give you the data to test, that said I am tring to parse x509 certificate templates.

Do I get some performance advantage in matching as OID constants instead of string?

Actually I am more intrested in trying to find a declarative way to parse all this kind of structure as those are really common and make parsing not so easy

**Comment by alex** [comment]
Yes, it's a significant performance improvement to compare via OID constants -- going via strings requires a bunch of allocations.

I'd be very interested in a declarative API for this, but I don't yet have any bright ideas :-) Hopefully you do.

**Comment by mtodescato** [comment]
I see as the only option using an enum to define from which tipes you can decide to parse the following element.
The main challenge of this is parsing efficiently, because if we parse by trial and error we may create a first implemententation to see how it goes.
The optimal way would be to incrementally parse the elements and therefore parse the data one time, clearly this would make more complex the way the library parses enum but it seems possible.

**Comment by alex** [comment]
There's no reason to parse by trial and error, we have an OID telling us which element to parse is.

Here's a first sketch of what an API might look like:

```rust
#[derive(Debug, asn1::Asn1Read, asn1::Asn1Write)]
pub struct QCStatement<'a> {
    #[defined_by_marker]
    statement_id: asn1::ObjectIdentifierMarker,
    #[defined_by(statement_id)]
    statement_info: Option<StatementInfo<'a>>,
}

#[derive(Debug, asn1::DefinedByRead, asn1::DefinedByWrite)]
pub enum StatementInfo<'a> {
    #[defined_by(some_oid)]
    QcEuRetentionPeriod(u32),
    #[defined_by(some_oid)]
    MonetaryValue(MonetaryValue<'a>),
    #[defined_by(some_oid)]
    QcType(QcType),
    #[defined_by(some_oid)]
    PSD2QcType(PSD2QcType<'a>),
    #[defined_by(some_oid)]
    QcEuPDS(PdsLocations<'a>),
}
```

**Comment by mtodescato** [comment]
Yes something like that seems reasonable
