### ISSUE TITLE
Help wanted: Parsing a given asn1 structure from bytes

### ISSUE THREAD

**Issue by YasinGuenduez-EH** [alex/rust-asn1#364]
Hello,

I just came across your library and have seen that you can use derive macros and wanted to test it with the following asn1 structure:

```
Session::= [APPLICATION 0] IMPLICIT SEQUENCE {
      a  [APPLICATION 10] IMPLICIT OCTET STRING (SIZE(8..32)),
      b  [APPLICATION 11] IMPLICIT OCTET STRING,
      c  [APPLICATION 31] IMPLICIT UTF8String (SIZE(1..512)) OPTIONAL,
      d  [APPLICATION 32] IMPLICIT OCTET STRING (SIZE(2..2)) OPTIONAL
}
```

I just do not know how to use the derive macro properly, so I can read my struct from given bytes. 
I tried it with the following struct - but obviously I am missing something (for example the `SIZE(x..z)`, but as far as I know this is not encoded).

```Rust
#[derive(asn1::Asn1Read)]
struct Session<'a> {
    #[implicit(10)]
    a: Option<&'a [u8]>,
    #[implicit(11)]
    b: Option<&'a [u8]>,
    #[implicit(31)]
    c: Option<asn1::Utf8String<'a>>,
    #[implicit(32)]
    d: Option<&'a [u8]>,
}
``` 

I tested it with a byte vector - just to get that piece successfully parsed.

```Rust
#[test]
fn parse_bytes_successfully() {
   let data: Vec<u8> = vec![
            0x60, 0x18, // Session
            0x4a, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // a
            0x4b, 0x2, 0x0, 0x2, // b
            0x5f, 0x1f, 0x2, 0x48, 0x69, // c
            0x5f, 0x20, 0x2, 0x1, 0x0, // d
        ];
   let session = asn1::parse_single::<Session>(&data);
   assert!(session.is_ok());
}
```

Can you give me a hint on how to use the derive properly, to get these bytes in the test parsed? Or is there something I am missing out? Thanks for your help in advance.

Best Yasin

**Comment by alex** [comment]
In this case your entire Sequence is wrapped in tag, so you need something like `asn1::parse_single::<Implicit<Session, Tag = 10>>(&data)` I believe.

You can also use `#[implicit(10, required)]` since the first two fields aren't `OPTIONAL`.

**Comment by YasinGuenduez-EH** [comment]
Thanks for the fast response! :)

I'll close the issue, as it helped.
