### ISSUE TITLE
Decoding of ObjectIdentifiers fails when encoding of individual OID components exceeds 4 octets

### ISSUE THREAD

**Issue by CBonnell** [alex/rust-asn1#408]
I believe this is a relatively rare occurrence, but I have encountered this limitation when attempting to parse "real life" certificates (not contrived test cases) with the `cryptography` library. My currently installed version of cryptography is using rust-asn1 0.15.2.

It appears that the `base128` module does not support decoding individual OID components whose encoding exceeds 4 octets: https://github.com/alex/rust-asn1/blob/main/src/base128.rs#L22. I don't believe any of the ASN.1 specifications (X.680, X.690, etc.) state that the encoding of individual OID components must not be greater than 4 octets. Additionally, and at least one other tool (in particular, pyasn1) appear to handle in the expected manner, so this appears to be a limitation specific to this library. As mentioned above, OIDs with these (abnormal) components are rare, but I want to report this behavior nonetheless.

Example OID that exhibits this issue: `2.16.840.1.113733.1.16.1.2.2.7.1.750304883`. The DER encoding of this OID is: `06 13 60 86 48  01 86 F8 45 01 10 01 02 02 07 01 82 E5 E2 FC 73`. Note that the encoding of the final component uses 5 octets.

Result when running `x509.ObjectIdentifier('2.16.840.1.113733.1.16.1.2.2.7.1.750304883')` in a Python console:

```python
x509.ObjectIdentifier('2.16.840.1.113733.1.16.1.2.2.7.1.750304883')
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: InvalidValue }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\asn1-0.15.2\src\object_identifier.rs:106:58
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1.4\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ParseError { kind: InvalidValue }
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: InvalidValue }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\asn1-0.15.2\src\object_identifier.rs:106:58
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: InvalidValue }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\asn1-0.15.2\src\object_identifier.rs:106:58
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: InvalidValue }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\asn1-0.15.2\src\object_identifier.rs:106:58

```

**Comment by alex** [comment]
That's correct that `ObjectIdentifier` only supports OIDs whose components fit in 32-bits. I think we'd be willing to consider going up to 64-bit components if there are relevant known OIDs that require it.

That said, it's a bug that this ever panics, it should always be returning a clean error on too-large inputs.

**Comment by reaperhulk** [comment]
@CBonnell the OID in question (1.3.6.1.4.1.311.97.327793017.823652640.593990854.550307053) is supported in current rust-asn1 and will be in cryptography 42.0.0.
