### ISSUE TITLE
How to use BigInt (or num::BigInt)

### ISSUE THREAD

**Issue by Tecol87** [alex/rust-asn1#423]
There was a PR adding support for num::BigInt. https://github.com/alex/rust-asn1/pull/24/files
This functionality seams to be removed, instead there is a BigInt class in this library. It can be created from already encoded data:
`Create a new BigInt from already encoded data.`
How can I easily encode my num::BigInt to the needed data?

**Comment by alex** [comment]
https://docs.rs/asn1/latest/asn1/struct.BigInt.html#method.new can be used to create a BigInt from bytes. 

How to encode the data in an appropriate way would be a better question for the `num` maintainers, but https://docs.rs/num/latest/num/struct.BigInt.html#method.to_signed_bytes_be looks like it's the right place to start.

**Comment by Tecol87** [comment]
Ok, thank you, I got this to work :)
