### ISSUE TITLE
linux: C shim

### ISSUE THREAD

**Issue by jarkkojs** [alex/rust-asn1#462]
`ASN1_RUST` opt-in would make sense for Linux kernel, and it is quite well-defined problem so I'll just describe it here.

API for the ASN.1 is `int asn1_ber_decoder(decoder, context, data, datalen)`.

`decoder` takes in a byte code program, and kbuild can generate such from ASN.1:

```
$(obj)/tpm2_key.asn1.o: $(obj)/tpm2_key.asn1.h $(obj)/tpm2_key.asn1.c
$(obj)/tpm2_key.o: $(obj)/tpm2_key.asn1.h
tpm-y += tpm2_key.o tpm2_key.asn1.o
```
This will result a symbol `tpm2key_decoder`, which then can be passed by as the value for `decoder` in `asn1_ber_decoder()`.

In order to implement ASN.1 decoder in Rust, and make it callable from C, the following features are required for the shim:

* Substitute `decoder` with some format that makes sense for the associated Rust crate.
* Substitute `scripts/asn1_compiler.c` with something that results a symbol with a backwards compatible name.
* Retain API compatibility, i.e. call sites would not optimally change but ignore ABI compatibility (e.g. does not have to be even byte code per se).

I put this here so that we can recall the topic quickly :-) But yeah, I think this is the gist of the problem (given low number of call sites, encoding **is not**).

**Comment by jarkkojs** [comment]
IMHO, some tweaks to makefiles is acceptable but API changes in the C source code are more time consuming. Would be possible but sub-optimal.

**Comment by jarkkojs** [comment]
And obvious fact but better always to be explicit on everything: any substitution exactly and only when `RUST_ASN1=y` ;-)

**Comment by jarkkojs** [comment]
I'm not a Rust expert but I do review C code on a daily basis and my gut feeling was that this makes most sense to me of all ASN.1 crates I could find, when it comes to Linux kernel. I.e. it has my full support going forward.

**Comment by reaperhulk** [comment]
Does the kernel need BER or DER? This library only supports DER at the moment.

**Comment by alex** [comment]
There's a few pieces here. Doing actual integration with the linux kernel is beyond the scope of this repository of course.

The first piece is making us work without `alloc`. This means making the writer parametrized by the output buffer. Ideally we'd support writing into `alloc::Vec`, a pre-allocated `&mut [u8]` (including one from a fixed size stack buffer!), or any user-provided buffer that implemented some trait. This is probably a shovel-ready project.

The second piece is, of course, actually emitting `extern "C"` functions. This will require some API design to figure out, so we should work through that design first. I'd be happy to see a proposal.

**Comment by jarkkojs** [comment]
> There's a few pieces here. Doing actual integration with the linux kernel is beyond the scope of this repository of course.
> 
> The first piece is making us work without `alloc`. This means making the writer parametrized by the output buffer. Ideally we'd support writing into `alloc::Vec`, a pre-allocated `&mut [u8]` (including one from a fixed size stack buffer!), or any user-provided buffer that implemented some trait. This is probably a shovel-ready project.
> 
> The second piece is, of course, actually emitting `extern "C"` functions. This will require some API design to figure out, so we should work through that design first. I'd be happy to see a proposal.

Hmm... So I gave this a thought and I agree what you are saying.

To make Rust ASN.1 happen in kernel with absolutely minimum intrusion would be write byte code interpreter to the output format of `scripts/asn1_compiler.c`.

Obviously you could re-write also the compiler in Rust but writing the interpreter part in Rust would the minimum amount of work to fully test kernel with some functionality enabled.

I.e. implement equivalent of `lib/asn1_decoder.c` in Rust, and turn that on if `CONFIG_ASN1_RUST` is enabled.

**Comment by alex** [comment]
I don't have any interest in supporting the bytecode compiler approach to decoding in this crate.

You may be able to use the imperative API for this crate to implement that yourself, but it's not in scope for this repo.

**Comment by jarkkojs** [comment]
So yeah thanks for the remarks, and I fully get your point of view. I've just learned the problem definition along the way, as I've looked more how the internals of the current implementation have been done. This anyway sorted out what is required to bind Rust to the existing infrastructure of ASN.1. So I guess we can close this then :-)

**Comment by jarkkojs** [comment]
> I don't have any interest in supporting the bytecode compiler approach to decoding in this crate.
> 
> You may be able to use the imperative API for this crate to implement that yourself, but it's not in scope for this repo.

Yep, I fully agree that within this crate it would not make any sense. It should be project of its own.

If the current code is ever refactored the Rust, it would probably make sense to refactor them in tandem. I.e. make what ASN.1 compiler generates to be most feasible for an ASN.1 decoder implemented in Rust.

I still think for kernel the current infra does make sense because it is easy for developer to use and ASN.1 formats are fixed per kernel build.

Sorry writing some remarks I have in mind for future reference, that's all.

**Comment by jarkkojs** [comment]
Yeah and one point of that infra is obviously that with a set of non-generic ASN.1 decoders, instead of one ASN.1 decoder, e.g. RSA key decoder will refuse to load anything at else than what is defined in the associated asn1 file during kernel build. So it has a point...
